[package]
name = "brutus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
nix = { version = "0.27", features = ["term", "process", "ioctl", "fs"] }
simple_logger = { version = "4", features = ["threads"] }
termion = "2"
tokio = { version = "1", features = ["full"] }
