[package]
name = "brutus"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["os-ext", "os-poll"] }
log = "0.4"
simple_logger = "4.3"
nix = { version = "0.27", features = ["term", "process"] }
termion = "3.0"
kanal = "0.1.0-pre8"
